image: node

before_script:
  - npm config set registry https://registry.npm.taobao.org/
  - npm install -g pnpm
  - pnpm config set registry https://registry.npm.taobao.org/
  - pnpm install
stages:
  - build
  - deploy
build-code:
  stage: build
  script:
    - echo "build code!"
    - pnpm build
cache:
  paths:
    - node_modules/
    - dist/

pages:
  stage: deploy
  script:
    - rm -rf public
    - mkdir -p public
    - mv dist/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment: production
